# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dbpass123
      - POSTGRES_USER=workflows
      - PGDATA=/var/lib/postgresql/data/pgdata

  test-py27:
    build:
      context: .
      dockerfile: tests/Dockerfile.py27
    command: tox -r
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - TOXENV=pep8,docs,doctests,docstyle,py27
  test-py27postgres:
    extends:
      service: test-py27
    depends_on:
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://workflows:dbpass123@postgres:5432/workflows
      - TOXENV=py27postgres

  test-py36:
    extends: test-py27
    build:
      context: .
      dockerfile: tests/Dockerfile.py36
    environment:
      - TOXENV=py36
  test-py36postgres:
    extends: test-py36
    depends_on:
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://workflows:dbpass123@postgres:5432/workflows
      - TOXENV=py36postgres
